trigger:
- master
- releases/*

jobs:

# All tasks on Linux
- job: build_all_linux_legacy
  displayName: Build all tasks using node 10 (Linux)
  variables:
    node_version: '10.x'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: azure-pipelines-template.yml

# All tasks on Windows
- job: build_all_windows
  displayName: Build all tasks (Windows)
  variables:
    node_version: '12.x'
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: azure-pipelines-template.yml

# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  variables:
    node_version: '12.x'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: azure-pipelines-template.yml

# All tasks on macOS
- job: build_all_darwin
  displayName: Build all tasks (macOS)
  variables:
    node_version: '12.x'
  pool:
    vmImage: macos-10.13
  steps:
  - template: azure-pipelines-template.yml
