name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: npm i
      - run: npm run build:grammar
      - run: npm test
      - run: npm run diff

      